///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityDataLinks {
/*
{
  "details": "https://turkishemarket.com/api/v2/products/13449",
  "reviews": "https://turkishemarket.com/api/v2/reviews/product/13449",
  "related": "https://turkishemarket.com/api/v2/products/related/13449",
  "top_from_seller": "https://turkishemarket.com/api/v1/products/top-from-seller/13449"
}
*/

  String? details;
  String? reviews;
  String? related;
  String? topFromSeller;

  SomeRootEntityDataLinks({
    this.details,
    this.reviews,
    this.related,
    this.topFromSeller,
  });
  SomeRootEntityDataLinks.fromJson(Map<String, dynamic> json) {
    details = json['details']?.toString();
    reviews = json['reviews']?.toString();
    related = json['related']?.toString();
    topFromSeller = json['top_from_seller']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['details'] = details;
    data['reviews'] = reviews;
    data['related'] = related;
    data['top_from_seller'] = topFromSeller;
    return data;
  }
}

class RelatedProductModel {
/*
{
  "id": 13449,
  "name": "GRUNDIG 40 Hamburg GDF 5955B LED TV",
  "photos": [
    "18123"
  ],
  "thumbnail_image": "uploads/all/FpyEYKPrxT8Hqol2lix6YoPIikHPYtds9rUI05Z5.jpg",
  "base_price": 737.382,
  "base_discounted_price": 737.382,
  "todays_deal": 0,
  "featured": 1,
  "unit": "pc",
  "discount": 0,
  "discount_type": "amount",
  "rating": 0,
  "sales": 0,
  "links": {
    "details": "https://turkishemarket.com/api/v2/products/13449",
    "reviews": "https://turkishemarket.com/api/v2/reviews/product/13449",
    "related": "https://turkishemarket.com/api/v2/products/related/13449",
    "top_from_seller": "https://turkishemarket.com/api/v1/products/top-from-seller/13449"
  }
}
*/

  int? id;
  String? name;
  List<String?>? photos;
  String? thumbnailImage;
  double? basePrice;
  double? baseDiscountedPrice;
  int? todaysDeal;
  int? featured;
  String? unit;
  int? discount;
  String? discountType;
  int? rating;
  int? sales;
  SomeRootEntityDataLinks? links;

  RelatedProductModel({
    this.id,
    this.name,
    this.photos,
    this.thumbnailImage,
    this.basePrice,
    this.baseDiscountedPrice,
    this.todaysDeal,
    this.featured,
    this.unit,
    this.discount,
    this.discountType,
    this.rating,
    this.sales,
    this.links,
  });
  RelatedProductModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    if (json['photos'] != null) {
      final v = json['photos'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      photos = arr0;
    }
    thumbnailImage = json['thumbnail_image']?.toString();
    basePrice = json['base_price']?.toDouble();
    baseDiscountedPrice = json['base_discounted_price']?.toDouble();
    todaysDeal = json['todays_deal']?.toInt();
    featured = json['featured']?.toInt();
    unit = json['unit']?.toString();
    discount = json['discount']?.toInt();
    discountType = json['discount_type']?.toString();
    rating = json['rating']?.toInt();
    sales = json['sales']?.toInt();
    links = (json['links'] != null) ? SomeRootEntityDataLinks.fromJson(json['links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (photos != null) {
      final v = photos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['photos'] = arr0;
    }
    data['thumbnail_image'] = thumbnailImage;
    data['base_price'] = basePrice;
    data['base_discounted_price'] = baseDiscountedPrice;
    data['todays_deal'] = todaysDeal;
    data['featured'] = featured;
    data['unit'] = unit;
    data['discount'] = discount;
    data['discount_type'] = discountType;
    data['rating'] = rating;
    data['sales'] = sales;
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}


