///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityCartItems {
/*
{
  "id": 2504,
  "owner_id": 12,
  "user_id": 92,
  "product_id": 11544,
  "product_name": "KARACA Bio Diamond Pro 30 cm 2,5 Lt Pan with Induction Base",
  "product_thumbnail_image": "uploads/all/V0Ni0gKgP3GW2jaUV3zfZUgRMcD2fMUL4PCH2PdD.jpg",
  "variation": null,
  "price": 88.9,
  "currency_symbol": "RS",
  "tax": 16.002,
  "shipping_cost": 0,
  "quantity": 4,
  "lower_limit": 1,
  "upper_limit": 5
}
*/

  int? id;
  int? ownerId;
  int? userId;
  int? productId;
  String? productName;
  String? productThumbnailImage;
  String? variation;
  double? price;
  String? currencySymbol;
  double? tax;
  int? shippingCost;
  int? quantity;
  int? lowerLimit;
  int? upperLimit;

  SomeRootEntityCartItems({
    this.id,
    this.ownerId,
    this.userId,
    this.productId,
    this.productName,
    this.productThumbnailImage,
    this.variation,
    this.price,
    this.currencySymbol,
    this.tax,
    this.shippingCost,
    this.quantity,
    this.lowerLimit,
    this.upperLimit,
  });
  SomeRootEntityCartItems.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    ownerId = json['owner_id']?.toInt();
    userId = json['user_id']?.toInt();
    productId = json['product_id']?.toInt();
    productName = json['product_name']?.toString();
    productThumbnailImage = json['product_thumbnail_image']?.toString();
    variation = json['variation']?.toString();
    price = json['price']?.toDouble();
    currencySymbol = json['currency_symbol']?.toString();
    tax = json['tax']?.toDouble();
    shippingCost = json['shipping_cost']?.toInt();
    quantity = json['quantity']?.toInt();
    lowerLimit = json['lower_limit']?.toInt();
    upperLimit = json['upper_limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['owner_id'] = ownerId;
    data['user_id'] = userId;
    data['product_id'] = productId;
    data['product_name'] = productName;
    data['product_thumbnail_image'] = productThumbnailImage;
    data['variation'] = variation;
    data['price'] = price;
    data['currency_symbol'] = currencySymbol;
    data['tax'] = tax;
    data['shipping_cost'] = shippingCost;
    data['quantity'] = quantity;
    data['lower_limit'] = lowerLimit;
    data['upper_limit'] = upperLimit;
    return data;
  }
}

class CardModel {
/*
{
  "name": null,
  "owner_id": 12,
  "cart_items": [
    {
      "id": 2504,
      "owner_id": 12,
      "user_id": 92,
      "product_id": 11544,
      "product_name": "KARACA Bio Diamond Pro 30 cm 2,5 Lt Pan with Induction Base",
      "product_thumbnail_image": "uploads/all/V0Ni0gKgP3GW2jaUV3zfZUgRMcD2fMUL4PCH2PdD.jpg",
      "variation": null,
      "price": 88.9,
      "currency_symbol": "RS",
      "tax": 16.002,
      "shipping_cost": 0,
      "quantity": 4,
      "lower_limit": 1,
      "upper_limit": 5
    }
  ]
}
*/

  String? name;
  int? ownerId;
  List<SomeRootEntityCartItems?>? cartItems;

  CardModel({
    this.name,
    this.ownerId,
    this.cartItems,
  });
  CardModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    ownerId = json['owner_id']?.toInt();
    if (json['cart_items'] != null) {
      final v = json['cart_items'];
      final arr0 = <SomeRootEntityCartItems>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityCartItems.fromJson(v));
      });
      cartItems = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['owner_id'] = ownerId;
    if (cartItems != null) {
      final v = cartItems;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cart_items'] = arr0;
    }
    return data;
  }
}
